name = "DynamicObjects"
uuid = "23d02862-63fe-4c6e-8fdb-1d52cbbd39d5"
authors = ["Nikolas Siccha <nikolassiccha@gmail.com> and contributors"]
version = "0.4.2"

[weakdeps]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[extensions]
SerializationExt = "Serialization"
SHAExt = ["SHA", "Serialization"]

[compat]
julia = "1"

[extras]
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SHA", "Serialization", "Test"]
